### ISSUE TITLE
Class names are undefined

### ISSUE THREAD

**Issue by Skorkmaz88** [drainingsun/boobs#2]
Loaded class names are 'undefined' in saved txt files, although class names were successfully loaded. I get the bounding box positions but labeled as undefined

**Comment by DataDigger88** [comment]
I'm having the same issue.

**Comment by DataDigger88** [comment]
I may have found the reason: the class names are read from the .txt file so that an additional newline character is included in each name. Therefore the code cannot find indices that match the annotated classes, and you get 'undefined' in the saved .txt files.

I don't know if this is the perfect / global solution, but it seems to be working at least for me:
In _boobs.js_ file, simply replace row 724:
`const rows = lines.split("\n")` 
with this row:
`const rows = lines.split("\r\n")`

**Comment by Skorkmaz88** [comment]
I think you should make that a PR

**Comment by drainingsun** [comment]
Thanks for finding the issue guys! Unfortunately, your fix will only work on Windows and will break Mac OS. So I will close the PR and make the necessary changes myself.
