### ISSUE TITLE
B-boxes recovery after PC power faliure

### ISSUE THREAD

**Issue by sharoseali** [drainingsun/boobs#5]
@drainingsun My PC shuts down because of Power Faliure.. after restarting the bboxes donot recover when i restore my browser,, serious shock... i was about to finish my work.......... i labeled 1000 images.. Help me please .......if u can recover my hard work

**Comment by keanedawg** [comment]
That's not really something that I think can easily be fixed. In general, I would work in small increments (say 50 images) in order to ensure that if something happens not too much is lost

**Comment by drainingsun** [comment]
Uh, ouch. Sorry to hear that. I will investigate whether there's a bug somewhere. Last time I checked it was working. For future, always save your work in increments. It's not hard to click "Save". I always do that no matter what kind of work I do.

**Comment by drainingsun** [comment]
So, I found out that if you were using Safari, it doesn't support localStorage if the file is opened directly  (file:///). There is a way around it, though. Check the attached image. "Disable Local File Restrictions" line must be checked. 
![boobs](https://user-images.githubusercontent.com/24862996/50544696-09926d00-0c32-11e9-8700-1ca798294c44.jpg)

Other options include:

Host Boobs somewhere online or;
Use Chrome or Firefox. They also have larger localStorage limits (5MB instead of 2.5MB in Safari). This can become an issue if you have tens of thousands of Bboxes. 

I've also pushed an update that warns user if localStorage is not supported so that users know they are not being protected from accidental crashes.
